keys:
  - &g age15e8xkkpw38y4mzfddkmpdhnt0xna4phypmfaed9x3ewxvl8td44s0gm77l
  - &gabz age15jcxjp49wajm27g9usseqz5cv5kj4ccp4n3e5ukzcyvf0fvuyyustngtpp

  # - &spacehound age172mwycpc633cguh9e0x0s9ytjm7u9eps69ec83u9shhs3rw83uss27fnzn

creation_rules:
  - path_regex: secrets/gabz\.yaml
    key_groups:
      - age:
          - *g
          - *gabz

  - path_regex: secrets/services/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *g
          - *gabz
